---
title: "BIOS 735 - Introduction to Statistical Computing"
author: "Naim Rashid"
output: 
  html_document:
    self_contained: false
---

### Course information

1:25-3:10 MW, on zoom <!-- - MC 1305 -->

Dr. Rashid's office hours: M <!-- @ MC 3104E --> (after class) <br>
Grader office hours: M 4-5, zoom


[Syllabus](syllabus.html)

### Schedule and course notes

For `Rmd` files, go to the
[course repo](https://github.com/biodatascience/statcomp_src) and navigate the
directories, or best of all to clone the repo and navigate within RStudio. 

| Week | Topic | Dir. | HW | HTML | Title |
|------|-------|------|----|------|-------|
| **Module 1**   | Sci. research | | | | |
| Jan 10      | R code | `rpkg` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/rpkg/rpkg_HW1.Rmd) | [efficient](rpkg/efficient.html) | Readable and efficient R code |
| Jan 12, 19 | R package | `rpkg` |  [hw](https://github.com/biodatascience/statcomp_src/blob/master/rpkg/rpkg_HW2.Rmd)| [build](rpkg/build.html) | Building an R package |
| | | | | [document](rpkg/document.html) | Documenting an R package |
| | | | | [test](rpkg/test.html) | Writing package tests |
| | | | | [debug](rpkg/debug.html) | Debugging in R |
| Jan  24     | C++ from R | `rpkg` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/rpkg/rpkg_HW3.Rmd) | [rcpp](rpkg/rcpp.html) | Calling C++ with `Rcpp` |
| Jan 26, 31 | Large data | `large` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/large/large_HW4.Rmd)| [datatable](large/datatable.html) | Working with `data.table` |
| | | | | [sqlite](large/sqlite.html) | Working with `RSQLite` |
| | | | | [hdf5](large/hdf5.html) | Working with `rhdf5` |
| | | | | [sparse](large/sparse.html) | Sparse data manipulation |
| **Module 2**   | Optim. & Num. int. | | | | |
| Feb 2, 7, 9   | General optim. | `optim` | [hw](https://github.com/biodatascience/statcomp_src/blob/master/optim/optim_HW5.Rmd)| [optim](optim/optim.html) | General optimization |
| Feb 14, 16 | EM algorithm | `em` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/em/em_HW6.Rmd)| [em](em/em.html) | EM algorithm |
| Feb 21, 23     | Numer. integration | `numint` | [hw](https://github.com/biodatascience/statcomp_src/blob/master/numint/numint_HW7.Rmd) | [numint](numint/numint.html) | Numerical integration |
| Feb 28, Mar 2, 7 | General MCMC | `mcmc` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/mcmc/mcmc_HW8.Rmd)  [hw2](https://github.com/biodatascience/statcomp_src/blob/master/mcmc/mcmc_HW9.Rmd) | [mcmc](mcmc/mcmc.html) | General MCMC |
| Mar 9, 14   | Advanced MCMC | `advmcmc` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/advmcmc/advmcmc_HW10.Rmd)| [advmcmc](advmcmc/advmcmc.html) | Advanced MCMC |
| **Module 3** | Mach. learning | | | | |
| Mar 16, 21, 23   | ML essentials | `ml` |   [hw](https://github.com/biodatascience/statcomp_src/blob/master/ml/essentials_HW11.Rmd) | [essentials](ml/essentials.html) | Machine learning essentials |
| Mar 28, 30  | SVM, RF | `ml` |  <!-- [hw](https://github.com/biodatascience/statcomp_src/blob/master/ml/svm_HW12.Rmd) -->| [svm](ml/svm.html) | Support vector machines |
| | | | | [rf](ml/rf.html) | Random forests |
| Apr 4, 6 | NN, Guest Lecture | `ml` | | [nn](ml/nn.html) | Neural networks |
| Apr 11, 13 | Projects | | | | |
| Apr 18, 20 | Projects, Wrap-up | | | | |
| Apr 25, 27 | Wrap-up | | | | |
---

This page was last updated on `r format(Sys.time(), "%m/%d/%Y")`. 

* [GitHub repo](https://github.com/biodatascience/statcomp_src)
* [License](https://github.com/biodatascience/statcomp_src/blob/master/LICENSE)
