---
title: "BIOS 735 - Introduction to Statistical Computing"
author: "Naim Rashid"
output:
  html_document: default
---

# Syllabus

### Course Description

Teaches important concepts and skills for statistical software development using case studies. After this course, students will have an understanding of the process of statistical software development, knowledge of existing resources for software development, and the ability to produce reliable and efficient statistical software

### Prerequisites - strictly enforced

* [BIOS 663 & 760 (or 762 if Bios DrPH)](https://sph.unc.edu/bios/courses/) 
* One programming class at the undergraduate level or [BIOS 611](https://biodatascience.github.io/datasci611/)
* Prior R experience is required, familiarity with [basic R functions](https://github.com/biodatascience/compbio_src/blob/master/eda/functions.md)
* Basic knowledge of the Linux environment

### Instructor

Dr. Naim Rashid <br>
Associate Professor <br>
Department of Biostatistics <br>

<br>
Office:  20-020 Lineberger<br>
email:  naim[at]unc.edu<br>
phone:  919-966-8150<br>
web:  https://naimurashid.github.io/ <br>

### Graders
Amber Young (ayoung31 at live.unc.edu) 

### Office Hours

Dr. Rashid's office hours: M 3:10-4pm (just see me after class) <br>
Grader office hours:  M 4-5, zoom  

### Course Website and Schedule

https://biodatascience.github.io/statcomp/

### Class Days, Times, Location

1:25-3:10 MW, MCG 1304

### Course Overview

This class teaches important concepts and skills for statistical
computing, numerical optimization, and machine learning using case
studies. After this course, students will have a good understanding of
the process of producing high-quality and sharable statistical
programs (module 1, 3 weeks), algorithms for optimization and numerical integration (module 2, 6 weeks), and will be able to implement and apply some common and powerful machine
learning methods (module 3, 3 weeks).  Modules 1 and 3 were originally developed by [Dr. Michael Love](https://mikelove.github.io). 



### Course Format
The course format will consist of bi-weekly lectures with optional readings (specified in the the lecture notes). Lectures are supplemented with in-class exercises, group activities, weekly homework, and projects. 

### Required Readings

There are no required texts for this course.  Any texts referenced in class lecture are either published online as open-access material or are available as free E-books through UNC libraries.

### Course-at-a-glance

The instructor reserves the right to make changes to the syllabus, including topics, readings, assignments, and due dates. In particular, availability of guest speakers may alter the course schedule. Any changes will be announced as early as possible. For the most recent session-by- session schedule and assignments, please see the course schedule at the following link: [https://biodatascience.github.io/statcomp/](https://biodatascience.github.io/statcomp/)

A general overview of topics is provided below.

#### Module 1 – Statistical Computing for Scientific Research (3 weeks)

* Writing readable and efficient R code
* Building, documenting, testing, and submitting an R package
* `Rcpp` for writing C++ code called from R
* Techniques for handling large datasets

#### Module 2 – Optimization and Numerical Integration (6 weeks)

* General Optimization (1.5 weeks)
    - Newton Raphson, fisher scoring, IRLS
    - BFGS, Nelder-Mead, gradient descent
* EM Algorithm (1 week)
    - EM, ECM 
    - Other variants: SEM, MCEM, Rejection Controlled EM
* General Numerical integration (1 week)
    - Gaussian Quadrature
    - Monte Carlo Integration
    - Importance Sampling 
* General Markov Chain Monte Carlo methods (1.5 week)
    - Direct and rejection sampling
    - Gibbs sampling
    - Metropolis Hastings
* Advanced MCMC (1 week)
    - Metropolis within Gibbs + adaptive variants
    - Hamiltonian MCMC
    - Scaling up: Variational Inference 
<!-- *Reversible jump MCMC -->
<!--* Constrained optimization (1 week) -->
<!--    - Linear and Quadratic Programming -->
<!--    - Penalized likelihood methods -->

#### Module 3 - Machine Learning Topics (3 weeks)

* Machine learning essentials
    - training and test sets
    - feature selection
    - parameter tuning
    - cross-validation
* Introductions to:
    - Support Vector Machines (SVM)
    - Random Forests (RF)
    - Neural Networks (NN)
    
### Course Assignments and Assessments
 
The class will be taught through three modules. One final project (30%), an initial proposal for the final project (10%), a final presentation (20%), and weekly homework assignments (40%) will make up the final grade for the course.  The initial proposal (due March 10th) can be resubmitted for a regrade as many times as desired up until March 31st.  

At the beginning of the course, students will learn to create an R
package which they will update as the class progresses, implementing
the methods they learn in each module. This R package will be
applied to each project and homework assignment. Each student's R
package will be hosted and iteratively updated on GitHub. Homework
and projects will be similarly submitted to course instructors through
GitHub Classrooms.  

Each student will also be assigned a Virtual Machine (VM) that contains all necessary software to run the course notes, examples, homework assignments, and class projects.  Students are also encouraged to install required course software locally on their own computers, where the VM provides an alternative if installation issues arise. Instructions for how to log into the VM will be sent out the first week of classes.  The VM instances are hosted on bios department servers, and any issues should be forwarded to bios IT.  

### Course Grading Scale:

* H: Clear excellence
* P: Entirely satisfactory
* L: Low passing
* F: Fail

The School of Public Health grading system is designed so that the
mode of the grading distribution is P. The last graded assignment will
be due on the last week of regular classes. 

*Homework policy* - students are allowed and encouraged to talk about ideas and approaches to homework problems in groups, though students should write up the code for the assignments **independently**. Copying someone else’s work is always an honor code violation.  Expulsion from the university is possible if the honor code is violated, and receiving 0% on the assignment in question is a certainty.  Late work will be penalized at 10% per week late.  

### Learning objectives

* How to write efficient and sharable statistical programs for scientific research
* Various optimization and numerical integration algorithms
* How to implement and use common and powerful machine learning methods

# Expectations, Policies, and Procedures

### Accessibility at UNC Chapel Hill

UNC-CH facilitates the implementation of reasonable accommodations, including resources and services, for students with disabilities, chronic medical conditions, a temporary disability, or pregnancy complications resulting in barriers to fully accessing University courses, programs and activities.  Accommodations are determined through the UNC Office of Accessibility Resources & Services (ARS), https://ars.unc.edu/; phone 919-962-8300; email ars@unc.edu. Students must document/register their need for accommodations with ARS before accommodations can be implemented.

### Attendance and Participation
Your attendance and active participation are an integral part of your learning experience in this course. If you are unavoidably absent, please notify the course instructor (and Teaching Assistant if one is assigned).

### Community Standards in Our Course and Mask Use.
UNC-Chapel Hill is committed to the well-being of our community – not just physically, but emotionally.  The indoor mask requirement was lifted for most of campus on March 7, 2022.  If you feel more comfortable wearing a mask, you are free to do so.  There are many reasons why a person may decide to continue to wear a mask, and we respect that choice.  For additional information, see [Carolina Together](https://carolinatogether.unc.edu/).

### Counseling and Psychological Services at UNC Chapel Hill
CAPS is strongly committed to addressing the mental health needs of a diverse student body through timely access to consultation and connection to clinically appropriate services, whether for short or long-term needs. Go to their website: https://caps.unc.edu, call them at 919-966-3658, or visit their facilities on the third floor of the Campus Health Services building for a walk-in evaluation to learn more.

### Honor Code
As a student at UNC Chapel Hill, you are bound by the university’s Honor Code, through which UNC maintains standards of academic excellence and community values. It is your responsibility to learn about and abide by the code.  All written assignments or presentations (including team projects) should be completed in a manner that demonstrates academic integrity and excellence. Work should be completed in your own words, but your ideas should be supported with well-cited evidence and theory.  If you have any questions about your rights and responsibilities, please consult the Office of Student Conduct (https://studentconduct.unc.edu/) or review the following resources:
*	Honor System
https://studentconduct.unc.edu/honor-system
*	Honor system module
https://studentconduct.unc.edu/students/honor-system-module
*	UNC Library’s plagiarism tutorial
https://guides.lib.unc.edu/plagiarism
*	UNC Writing Center’s handout on plagiarism
https://writingcenter.unc.edu/tips-and-tools/plagiarism/

### Inclusive Excellence 

We are committed to expanding diversity and inclusiveness across the School — among faculty, staff, students, on advisory groups, and in our curricula, leadership, policies and practices. We measure diversity and inclusion not only in numbers, but also by the extent to which students, alumni, faculty, and staff members perceive the School’s environment as welcoming, valuing all individuals, and supporting their development.

For more information about how we are practicing inclusive excellence at the Gillings School, visit our Diversity and Inclusion webpages:
*	Diversity and Inclusion: https://sph.unc.edu/resource-pages/diversity/ 
*	Minority Health Conference: http://minorityhealth.web.unc.edu/
*	National Health Equity Research Webcast: https://sph.unc.edu/mhp/nat-health-equity-research-webcast/

### Land Acknowledgement
Please read The Gillings School’s [Land Acknowledgement](http://sph.unc.edu/diversity/land-acknowledgement/). 

### Student Feedback and Equity Concerns
The Gillings School has in place a [mechanism for students to provide feedback](https://feedback.sph.unc.edu/), including specifically equity concerns and bias-related issues. You can use this form to describe feedback, both positive and negative, about anything including issues related to your experience as a student at Gillings, administrative processes, and classroom activities. This form will also allow you to specifically describe incidents in which racial or other equity-related bias, or microaggressions, occurred. You may submit this form anonymously. However, for us to follow up and provide the necessary support, we encourage you to include your contact information. For further information, please visit the [Student Feedback and Equity Concerns FAQ](https://sph.unc.edu/students/student-feedback-and-equity-concerns-faq/).
Please note that this form does not take the place of any University process or policy. If you would like to report an incident under the University’s policy on Prohibited Discrimination, Harassment, and Related Misconduct including Sexual and Gender Based Harassment, Sexual Violence, Interpersonal Violence, and Stalking, please visit [Safe At UNC](https://safe.unc.edu/) or the [Equal Opportunity and Compliance Office (EOC)](https://eoc.unc.edu/) for additional information, including resources, contact, and reporting options.

### Technical support
The best way to help prevent technical issues from causing problems for assignments is to submit them at least 24-36 hours before the due date and time.  Your instructor cannot resolve technical issues, but it’s important to notify them if you are experiencing issues. If you have problems submitting an assignment or taking a quiz in Sakai, immediately do the following:
1.	Contact the UNC Information Technology Services (ITS) department or Bios IT with the time you attempted to do your course action and what the course action was.
2.	Email your instructor with the information you sent to ITS/Bios IT and what time you sent the information.

The ITS department provides technical support 24-hours per day, seven days per week.  If you need computer help, please contact the ITS Help Desk by phone at +1-919-962-HELP (4357), or by [online help request](http://help.unc.edu/help/olhr), or by [UNC Live Chat](http://help.unc.edu/chat.).

### Title IX at UNC Chapel Hill
Any student who is impacted by discrimination, harassment, interpersonal (relationship) violence, sexual violence, sexual exploitations, or stalking is encouraged to seek resources on campus or in the community.  Please contact the Director of Title IX Compliance / Title IX Coordinator ([Adrienne Allison](mailto:adrienne.allison@unc.edu)), [Report and Response Coordinators in the Equal Opportunity and Compliance Office](mailto:reportandresponse@unc.edu), Counseling and Psychological Services (confidential), or the [Gender Violence Services Coordinators](mailto:gvsc@unc.edu) (confidential) to discuss your specific needs.  Additional resources are available at the “Safe at UNC” [website](https://safe.unc.edu/). 


---

This page was last updated on `r format(Sys.time(), "%m/%d/%Y")`. 

* [GitHub repo](https://github.com/biodatascience/statcomp_src)
* [License](https://github.com/biodatascience/statcomp_src/blob/master/LICENSE)
